### ISSUE TITLE
Provide readme/documentation

### ISSUE THREAD

**Issue by XuluWarrior** [duxtinto/github-cr-intellij-plugin#29]
I've installed the plugin and the GitHub Reviews tab just says "Nothing to see here"

I'm assuming that I need to configure it somewhere but can't see where.

I'm working on a private repository if that makes any difference.

**Comment by aaron-coolfront** [comment]
I'm having the same issue as XuluWarrior.  Don't know how to get the plugin to show any reviews.

**Comment by duxtinto** [comment]
Hi @XuluWarrior !
you are right... documentation is one of the pending things that I have to do :sweat_smile: .
The plugin doesn't have any configuration settings so far.
The authentication is done by the jetbrains github plugin, so if you have correctly set your github credentials in intellij (please, check this page to find how to: https://www.jetbrains.com/help/idea/github.html), the plugin should be fully configured, and you should be able of accessing even private repositories (the company that I work for uses them, and I can see their pull requests on the plugin).
Please, check if your github credentials are properly set, and let me know if you still can see the pull requests. ok?

Regards,
David.

**Comment by aaron-coolfront** [comment]
Hi @duxtinto,

I have my Github credentials correct in the WebStorm settings. I even clicked the 'Test' button on the Github setup page and it says 'Connection Successful'.  I too am part of an organization that uses private repositories.

Is there any logging anywhere that I might be able to check?

Regards,
Aaron

**Comment by duxtinto** [comment]
Hi @XuluWarrior & @aaron-coolfront !

Apart from configuring the github credentials on intellij, these are some other things that could be causing your problem:
- only pull requests belonging to the 'root repository' (the one in your project root folder) are detected
- your 'root repository' need to have a git remote (https://stackoverflow.com/questions/17067566/adding-a-remote-git-repo-through-intellij), called 'origin' or 'github' pointing to your github repository (see attached picture to see mine)
![git remotes_017](https://user-images.githubusercontent.com/333268/37114824-b453be48-2249-11e8-9d2e-ab62ef74fff0.png)

Please, try these settings, and let me know if it's fixing your problem. ok?

Regards,

David.

**Comment by duxtinto** [comment]
Hi @aaron-coolfront !

> I have my Github credentials correct in the WebStorm settings. I even clicked the 'Test' button on the Github setup page and it says 'Connection Successful'. I too am part of an organization that uses private repositories.

Apart from creating the git remote as indicated above, please, try to create a pull request by using the webstorm's functionality (https://www.jetbrains.com/help/webstorm/creating-a-pull-request.html)... if this works, and you can create a pull request in your private repository, as this plugin is using internally the same functions as webstorm github plugin to connect to the github api, we can discard that the problem is related to the private part of the repository 

> Is there any logging anywhere that I might be able to check?

No sorry, there isn't (this is my first attempt of creating an intellij plugin, and I don't even know how to log anything :sweat_smile:).
I have created a ticket in my issue tracker system for adding some logging in the future, but for now we will have to find a solution to your problem without it :sweat_smile: .

**Comment by aaron-coolfront** [comment]
@duxtinto 

I have my remotes setup properly.

I changed my Github account access from Password to Token in WebStorm.

I tried your suggestion of 'Create Pull Request' from WebStorm but I get:

> Can't Create Pull Request  
> Push failed: Could not read from remote repository.

But from what I read this is a different issue with Git and ssh, etc.

So, I tried out your plugin in my Intellij setup and got it to work.  I'm trying to understand the features of this plugin now.  Am I correct in thinking there isn't really any 'reviewer' features other than clicking the link that takes you to the github pull request (conversation)?  For example it doesn't allow for a 'reviewer' to make direct comments on given lines in files from within the IDE, does it?

Thank you.
Aaron

**Comment by duxtinto** [comment]
> So, I tried out your plugin in my Intellij setup and got it to work. I'm trying to understand the features of this plugin now. Am I correct in thinking there isn't really any 'reviewer' features other than clicking the link that takes you to the github pull request (conversation)? For example it doesn't allow for a 'reviewer' to make direct comments on given lines in files from within the IDE, does it?

yes, that's right... so far the reviewer part is not doing too much.
I'm currently working on this user story:

> As a reviewer, I want to quickly checkout the pull request branch with the latest changes

as I need it done in order to work on the one that you are talking about:

> As a reviewer, I want to create comments directly from intellij

**Comment by XuluWarrior** [comment]
I had another try at getting the plugin working.  As @aaron-coolfront reported it breaking in WebStorm but working in IntelliJ, I downloaded that to try it in that IDE.  However, I got the same behaviour.

I tried creating new tokens, both manually and using the "Create API Token" button in the IDE.  I was wondering if the token had to have any additional scopes but even creating one with all the scopes enabled didn't work.

I also tried creating a pull request in the IDE and that works fine.

What I did notice is that I get an error that I had missed before

```
Parameter specified as non-null is null: method com.duxtinto.intellij.plugin.github.codereviews.domain.pullrequests.issues.GetAllClosableByInteractor.run, parameter request
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.duxtinto.intellij.plugin.github.codereviews.domain.pullrequests.issues.GetAllClosableByInteractor.run, parameter request
	at com.duxtinto.intellij.plugin.github.codereviews.domain.pullrequests.issues.GetAllClosableByInteractor.run(GetAllClosableByInteractor.kt)
	at com.duxtinto.intellij.plugin.github.codereviews.net.pullrequests.apiv3.PullRequestResponseMapper.getClosableIssues(PullRequestResponseMapper.kt:36)
	at com.duxtinto.intellij.plugin.github.codereviews.net.pullrequests.apiv3.PullRequestResponseMapper.toEntity(PullRequestResponseMapper.kt:21)
	at com.duxtinto.intellij.plugin.github.codereviews.net.pullrequests.apiv3.PullRequestResponseMapper.toEntity(PullRequestResponseMapper.kt:11)
	at com.duxtinto.intellij.plugin.github.codereviews.ide.acl.services.github.pullrequests.IdeaPullRequestLoader.loadAll(IdeaPullRequestLoader.kt:35)
	at com.duxtinto.intellij.plugin.github.codereviews.net.pullrequests.apiv3.PullRequestFetcher.fetchAllForRepository(PullRequestFetcher.kt:20)
	at com.duxtinto.intellij.plugin.github.codereviews.data.pullrequests.PullRequestRepository.getAllMyAssignedBy(PullRequestRepository.kt:26)
	at com.duxtinto.intellij.plugin.github.codereviews.domain.pullrequests.GetAllMyAssignedForRepoInteractor.run(GetAllMyAssignedForRepoInteractor.kt:12)
	at com.duxtinto.intellij.plugin.github.codereviews.domain.pullrequests.GetAllMyAssignedForRepoInteractor.run(GetAllMyAssignedForRepoInteractor.kt:6)
	at com.duxtinto.intellij.plugin.github.codereviews.ide.acl.events.repositories.GitChangeListener.mappingChanged(GitChangeListener.kt:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by duxtinto** [comment]
Hi @XuluWarrior ! 

The stack trace that you have posted is pointing something really interesting... 
in order to find the issues that are closed by an specific pull request, I parse the pull request description that is returned from the github api, in search of any 'closing issues' keywords (https://help.github.com/articles/closing-issues-using-keywords/).

it looks that for you pull request, github api is returning a null description (and that is causing the crash)... my first hunch is that maybe it's happening because your pull request description is empty. Is that the case?
if the answer is yes, could you please add some text into the pull request description, and check if you are getting the same error?
Thanks.

**Comment by XuluWarrior** [comment]
I decided to try debugging the exception and after much faffing with IntelliJ (I'm not a Java developer) I found that the issue is with null descriptions on PRs.

I have created a PR (https://github.com/duxtinto/github-cr-intellij-plugin/pull/37) which resolves the issue for me.

**Comment by duxtinto** [comment]
Hi @XuluWarrior ! 

Thank you very much for your help! :).
I'm going to merge your PR, and it will be part of the next release.

Apart from fixing the problem, I think that the title of your issue still makes too much sense :sweat_smile: , so I have prioritized this user story related to documenting the available features (https://www.pivotaltracker.com/story/show/153954997)

Best regards,

David.

**Comment by duxtinto** [comment]
Hi @XuluWarrior ! 

I have just uploaded the new version (1.0.4), which contains your fix, into the jetbrains repository, so hopefully it will be publicly available in a couple of days.

**Comment by ryanbrainard** [comment]
+1 on at least some simple documentation. The way things are now, it's not very discoverable how to use this plugin.

**Comment by duxtinto** [comment]
Hi @ryanbrainard !

Being honest, since Jetbrains has already started to work on the ticket in charge of integrating Github code reviews, I feel that this plugin won't be useful anymore quite soon, so I have basically stop working on it.

**Comment by XuluWarrior** [comment]
Hi @duxtinto 
What's the Jetbrains ticket for their code review work?  I would be interested to know there progress and when we can expect it to be released.

**Comment by duxtinto** [comment]
Hi @XuluWarrior !

Is this one: https://youtrack.jetbrains.com/issue/IDEA-85079

**Comment by ryanbrainard** [comment]
@duxtinto Fair enough, but do you know if they are actually working on it? From the comments on there, it sounds like it's been languishing for 6 years.

**Comment by duxtinto** [comment]
I really think so... I started the plugin because that issue was 6 years old :laughing:, and because jetbrains was supporting Github Code reviews in upsource, but not directly on the IDEs... recently they have changed the ticket status to work in progress... my thoughts are that, at one hand, after 6 years of languishing, it doesn't make sense to change that status unless they really plat to start working on it, but at the other hand, as this move can take potential clients out of their upsource solution, I'm not sure of what the final result would be :sweat_smile:.

Let's give them some confidence, and see what happens.
