### ISSUE TITLE
IntelliJ 2018.1.1 EAP causes Exception

### ISSUE THREAD

**Issue by diskostu** [duxtinto/github-cr-intellij-plugin#40]
StackTrace after IDE startup:

`Parse exception while converting JSON to object class com.duxtinto.intellij.plugin.github.codereviews.net.codereviews.apiv3.RequestedReviewersResponse
org.jetbrains.plugins.github.exceptions.GithubJsonException: Parse exception while converting JSON to object class com.duxtinto.intellij.plugin.github.codereviews.net.codereviews.apiv3.RequestedReviewersResponse
	at org.jetbrains.plugins.github.api.GithubApiUtil.fromJson(GithubApiUtil.java:75)
	at com.duxtinto.intellij.plugin.github.codereviews.ide.acl.services.github.codereviews.IdeaCodeReviewerLoader.loadAllForPullRequest(IdeaCodeReviewerLoader.kt:25)
	at com.duxtinto.intellij.plugin.github.codereviews.net.codereviews.apiv3.CodeReviewerFetcher.fetchAllByPullRequest(CodeReviewerFetcher.kt:19)
	at com.duxtinto.intellij.plugin.github.codereviews.data.pullrequests.PullRequestRepository.getAllMyRequestedBy(PullRequestRepository.kt:38)
	at com.duxtinto.intellij.plugin.github.codereviews.domain.pullrequests.GetAllMyRequestedForRepoInteractor.run(GetAllMyRequestedForRepoInteractor.kt:11)
	at com.duxtinto.intellij.plugin.github.codereviews.domain.pullrequests.GetAllMyRequestedForRepoInteractor.run(GetAllMyRequestedForRepoInteractor.kt:6)
	at com.duxtinto.intellij.plugin.github.codereviews.ide.acl.events.repositories.GitChangeListener.mappingChanged(GitChangeListener.kt:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:426)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:387)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:376)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:364)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:357)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:43)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:208)
	at com.sun.proxy.$Proxy117.mappingChanged(Unknown Source)
	at com.intellij.dvcs.repo.VcsRepositoryManager.checkAndUpdateRepositoriesCollection(VcsRepositoryManager.java:225)
	at com.intellij.dvcs.repo.VcsRepositoryManager.directoryMappingChanged(VcsRepositoryManager.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:426)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:387)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:376)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:364)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:357)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:43)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:208)
	at com.sun.proxy.$Proxy74.directoryMappingChanged(Unknown Source)
	at com.intellij.openapi.vcs.impl.projectlevelman.NewMappings.mappingsChanged(NewMappings.java:186)
	at com.intellij.openapi.vcs.impl.projectlevelman.NewMappings.activateActiveVcses(NewMappings.java:125)
	at com.intellij.openapi.vcs.impl.projectlevelman.NewMappings.lambda$new$0(NewMappings.java:94)
	at com.intellij.openapi.vcs.impl.VcsInitialization.execute(VcsInitialization.java:103)
	at com.intellij.openapi.vcs.impl.VcsInitialization.access$000(VcsInitialization.java:43)
	at com.intellij.openapi.vcs.impl.VcsInitialization$1.run(VcsInitialization.java:67)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:953)
	at com.google.gson.Gson.fromJson(Gson.java:926)
	at org.jetbrains.plugins.github.api.GithubApiUtil.fromJson(GithubApiUtil.java:70)
	... 53 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
	at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:162)
	at com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:87)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
	... 57 more`

**Comment by diskostu** [comment]
Hi there,

do you have any news for this issue?

**Comment by duxtinto** [comment]
Hi @diskostu ! 
Sorry for the late answer.

I haven't got time yet to take a look to the issue, but I'll take a look as soon as I finish the issue that I'm working on right now.

**Comment by itaysanyvision** [comment]
In 2018.1
Cannot load project: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing plugin main.com.duxtinto.intellij.plugin.github.codereviews

**Comment by duxtinto** [comment]
Hi @diskostu & @itaysanyvision !

I'm trying to reproduce this issue on 2018.1, but I couldn't:
![intellij_2018 1_error](https://user-images.githubusercontent.com/333268/39088016-319494ac-45ab-11e8-9a34-2fcff18d5c9a.png)

Could you guys please tell me what is the exact version number that you are using?

**Comment by robertjmason** [comment]
I just got this same error... here's the version info:

IntelliJ IDEA 2018.1.2 EAP (Ultimate Edition)
Build #IU-181.4668.1, built on April 10, 2018
JRE: 1.8.0_152-release-1136-b29 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.11.6
